### ISSUE TITLE
MVP coordination

### ISSUE THREAD

**Issue by ericgroom** [sfsu-csc-668-spring-2019/term-project-teamtabs-dousuru#15]
I don't know how you guys feel, but I feel like we have a lot of extra features that aren't going to be finished in time, or at least we should plan that some things are not going to be finished in time. So I suggest that we create a list of absolute essentials that we need to do a demo. 

Here are my suggestions:
Being able to view an organization, create an organization
Being able to CRUD projects and tasks.
Authentication/Authorization

Next level priorities:
Socket updates
Notifications
Basic chat
Permissions system

Low priority:
Making it look nice
Multimedia chat

**Comment by mwinata94** [comment]
Back end progress has been slow bc I haven't put in much effort. I'll pitch in more efforts from now on, and I should be able to complete the back end before Monday class meeting
